# .github/workflows/deploy-blazor.yml
name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'  # Ajuste conforme necessário

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet publish -c Release -o build

    - name: Copy files to temp
      run: |
        mkdir temp
        cp -r build/wwwroot/* temp/

    - name: Update <base href> in index.html for GitHub Pages
      run: |
        sed -i 's|<base href=".*" />|<base href="/Portifolio/" />|' temp/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./temp

