# .github/workflows/deploy-blazor.yml
name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - main  # ou a branch que você usa como principal

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' # ou a versão que seu projeto usa

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet publish -c Release -o build

    - name: Copy files
      run: |
        mkdir temp
        cp -r build/wwwroot/* temp/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./temp
